name: Bug report
title: 'Bug:'
labels: 'Type: Bug'
assignees: []
body:
    - type: markdown
      attributes:
        value: |
          Thanks for taking the time to fill out this bug report. This will help us to improve Zeebe.
    - type: textarea
      attributes:
        label: Bug Description
        description: A clear and concise description of what the bug is.
      validations:
        required: true
    - type: markdown
      attributes:
        value: Any additional information that will help us in diagnosing the issue
    - type: textarea
      attributes:
        label: Reproduction Steps
        description: |
          Steps to reproduce the behavior.
          If possible add a minimal reproducer code sample
            - when using the Java client: https://github.com/zeebe-io/zeebe-test-template-java
    - type: textarea
      attributes:
        label: Expected Behavior
        description: A clear and concise description of what you expected to happen.
    - type: textarea
      attributes:
        label: Logs
        description: Log output that is related to the bug.
    - type: textarea
      attributes:
        label: Stacktrace
        description: Stacktrace that describes the bug.
    - type: input
      attributes:
        label: OS
        description: e.g. Linux. 
    - type: input
      attributes:
        label: Zeebe Version
        description: e.g. 1.2.1. 
    - type: input
      attributes:
        label: Configuration
        description: e.g. exporters etc. 
